name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image and deploy
        run: |
          ssh -o StrictHostKeyChecking=no 137.184.221.165 << 'EOF'
            # Navegar al directorio de tu aplicación
            cd /tools/node_appoiment/appoiment_backend

            # Detener y eliminar el contenedor antiguo
            docker stop appoiment_app || true
            docker rm appoiment_app || true

            # Construir la nueva imagen de Docker
            docker build -t app-image:latest .

            # Iniciar un nuevo contenedor en la red 'net-app'
            docker run -d --name appoiment_app --network net-app app-image:latest
          EOF
